---
- name: docker | Configure Disk Part
  parted:
    device: "{{ docker_lvm_device }}"
    number: 1
    flags: [ lvm ]
    state: present

  
- name: docker | Configure VG
  lvg:
    vg: docker
    pvs: "{{ docker_lvm_device }}1"
  register: vg_created


- name: docker | Configure LV thinpool
  lvol:
    vg: docker
    lv: thinpool
    size: 95%VG
    opts: --wipesignatures y
  register: lv_created_thinpool
  when: vg_created.changed


- name: docker | Configure LV thinpoolmeta
  lvol:
    vg: docker
    lv: thinpoolmeta
    size: 1%VG
    opts: --wipesignatures y
  register: lv_created_thinpoolmeta
  when: vg_created.changed


- name: docker | Convert LV to thin pool
  command: lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
  when: 
    - lv_created_thinpool.changed
    - lv_created_thinpoolmeta.changed


- name: docker | Setup Profile thinpool
  copy: 
    content: |
      activation {
         thin_pool_autoextend_threshold=80
         thin_pool_autoextend_percent=20
      } 
    dest: /etc/lvm/profile/docker-thinpool.profile
  register: thinpool_profile


- name: docker | Enable profile LV docker thinpool
  command: lvchange --metadataprofile docker-thinpool docker/thinpool 
  when: thinpool_profile.changed


- name: docker | Enable monitoring LVM
  command: lvs -o+seg_monitor
  when: thinpool_profile.changed


- name: docker | Create directory /etc/docker
  file: path=/etc/docker state=directory


- name: docker | Enable LVM Storage in Docker Service
  copy:
    content: |
      {
        "storage-driver": "devicemapper",
        "storage-opts": [
          "dm.thinpooldev=/dev/mapper/docker-thinpool",
          "dm.use_deferred_removal=true",
          "dm.use_deferred_deletion=true"
        ]
      }
    dest: /etc/docker/daemon.json
